version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_biblioteca
    working_dir: /var/www
    volumes:
      - ./:/var/www:delegated
    networks:
      - laravel

  webserver:
    image: nginx:alpine
    container_name: server_biblioteca
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www:delegated
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: db_biblioteca
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Biblioteca
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
    driver: local
